// ===== ボーカル定義 =====
// index: 0=ティラミス, 1=タルト, 2=よもぎ, 3=だいふく
const VOCALS = [
    { name: 'ティラミス', icon: './data/1.png' },
    { name: 'タルト',     icon: './data/2.png' },
    { name: 'よもぎ',     icon: './data/3.png' },
    { name: 'だいふく',   icon: './data/4.png' },
];

// ===== 楽曲データ =====
// vocals: [ティラミス, タルト, よもぎ, だいふく] の真偽値
// releaseDate: "YYYY-MM-DD"
const songs = [
    {
        title: '月下',
        youtubeUrl: 'https://www.youtube.com/embed/KD0cKlT9xVo?si=XzuAzSlDU7kae86Q',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '曲構成などを考えて作った初めての曲です。ソミドラ（GECA）から始まるので「月下」という名前になりました。',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '不明',
    },
    {
        title: 'nostalgie',
        youtubeUrl: 'https://www.youtube.com/embed/vHyaFPN8_4w?si=Hmsslv0Eq71h8rZq',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '不明',
    },
    {
        title: '夕空',
        youtubeUrl: 'https://www.youtube.com/embed/DJX6sND6MYU?si=ci84hCNGXXmkEqjM',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '不明',
    },
    {
        title: '時雨',
        youtubeUrl: 'https://www.youtube.com/embed/rz7EDExmefA?si=i2PUIV3TJkp_zQy8',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '不明',
    },
    {
        title: '下萌',
        youtubeUrl: 'https://www.youtube.com/embed/ni_oPfe7yCs?si=LlIx_DgP190zaA5O',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '作詞を始めてからはカノン進行をよく使うようになりましたが、始めてカノン進行を使った曲はこの曲だったりします。',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2023-03-20',
    },
    {
        title: 'SPLASH',
        youtubeUrl: 'https://www.youtube.com/embed/NuhCkYAmBCA?si=ufwYU_6ViomQgjkG',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2023-05-28',
    },
    {
        title: '紫陽花',
        youtubeUrl: 'https://www.youtube.com/embed/kArireXB8xI?si=2h2IN2dt-uQQnU1E',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '当時は 6/8 拍子だと思っていましたが、今思うとスウィングの 4/4 拍子です。',
        lyrics: '',
        bpm: '',
        timeSignature: '4/4',
        key: '',
        releaseDate: '2023-07-12',
    },
    {
        title: 'アキザクラ',
        youtubeUrl: 'https://www.youtube.com/embed/v6Sx-GP8Lho?si=b0qT_U7L-yrkE-Vh',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2023-09-19',
    },
    {
        title: '木枯らし',
        youtubeUrl: 'https://www.youtube.com/embed/TyA_O_8bosQ?si=gahD4FhSHWQr2FEQ',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '不明',
    },
    {
        title: 'autumn evening',
        youtubeUrl: 'https://www.youtube.com/embed/Lq8TiPkN-54?si=nVtnA6Z2zkA5NfkT',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '和訳すると「秋の夕暮れ」です。',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2023-11-22',
    },
    {
        title: '三日月',
        youtubeUrl: 'https://www.youtube.com/embed/RysUYnBEHCw?si=oljfMIBBG7RnLbUY',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '初めての変拍子曲です。三日月という名前を付けた理由は以下の3つです。・三日月の綺麗な季節に作ったから・3拍子だから・変拍子で1拍欠けているところが月が欠けているようだから',
        lyrics: '',
        bpm: '',
        timeSignature: '3/4',
        key: '',
        releaseDate: '2023-11-29',
    },
    {
        title: 'bloom snow',
        youtubeUrl: 'https://www.youtube.com/embed/M3wXkBc6sAY?si=L4iGQRoARTloeoLg',
        instrumentalUrl: '',
        basedOn: '',
        vocals: [false, false, false, false],
        comment: '後によく使うようになるコンファメーション進行というコード進行を初めて使った曲です。',
        lyrics: '',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '不明',
    },
    {
        title: 'ELSE',
        youtubeUrl: 'https://www.youtube.com/embed/3D9j7dvY-S8?si=9mLkVr8DIZ-hVquE',
        instrumentalUrl: 'https://www.youtube.com/embed/if-Cc2Ckf3U',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「大丈夫、失敗したとしても新たな道が待っている」\n初めて作詞をした曲です。プログラミングにおいて ELSE とは条件を満たさなかった場合の処理を書くときに使います。プログラミング用語で韻を踏んでいたりもします。',
        lyrics: 'コードの実態　高度の失敗\nプログラムのプロブレム\n関数のテスト　変数もですと\nどんなエラーも怖くない\n\n明日何があるか\n分からなくてもいい\n日常は条件分岐だから\n\nこうやって　ああやって　どうなっても大丈夫\nIFで失敗したら\nELSEがあるから\nこうやって　ああやって　止まったってまだ行ける\nELSE IFの先には\nELSEが待ってるから\n\n相対PATH　早退PASS\nUIという愛を込めて\nクライアント　暗い案も\nデプロイすれば明るくなる\n\n昨日何があったか\n忘れていてもいい\nグレードアップしていこう\n\nこうやって　ああやって　どうなっても大丈夫\nIFで上手くいかなかったら\nELSEがあるから\nこうやって　ああやって　止まったってまだ行ける\nELSE IFの先には\nELSEが待ってるから',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-02-16',
    },
    {
        title: 'コオペレイト',
        youtubeUrl: 'https://www.youtube.com/embed/IoJaEEc87eU?si=NPS1TrOu18eh9PYE',
        instrumentalUrl: 'https://www.youtube.com/embed/nNC4deB0ap4',
        basedOn: 'ELSE',
        vocals: [true, false, false, false],
        comment: '「1日は協力して作るもの、人生は合作だから」\nコオペレイト（cooperate）は「協力する」という意味です。ELSE とこの曲はまず作詞をして歌詞に合わせて曲を作っています。',
        lyrics: '朝起きたら　呼ぶ鳥の声\n新しい　1日が始まる\n雲一つない　空見上げれば\n清々しい　暁が輝く\n\nおはようから始まる\n昨日の続きが\n二人で開く　扉\n\n虹の橋のような　広い大地を\n一緒に駆ければ　寂しくない\n真っ白なキャンバス　心を映して\nわくわくで染めれば　楽しくなる\n\n夜寝るとき　ふと思い出す\n素晴らしい　今日蘇る\n傷一つない　外顔出せば\n輝かしい　星空が灯る\n\nおやすみで出来上がる\n今日の物語\n二人だけの　世界\n\n疲れてしまったら　思い出すから\n暖かい想いは　繋がっていく\nベストじゃなくていい　無理しないでと\n言ってくれたよね　嬉しかったよ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-02-26',
    },
    {
        title: 'ペースメーカー',
        youtubeUrl: 'https://www.youtube.com/embed/fTTuQeGkaCc?si=a8mUKaJCxeFy4ioM',
        instrumentalUrl: 'https://www.youtube.com/embed/AXRGBtOzP_U',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「前を行くものを追いかければ、どこまでだっていける」\n「ペースメーカー」は医療機器のことではなく、レースの走者を引っ張る役目のある人のことです。',
        lyrics: '隣り合わせ　足りない\nお気に入りの　テンポで\nあの日のまま　進もう\n時計の針　止まらないから\n\n見たこともない　だけど\n近くにあるの　きっと\n誰も知らない　そんな\n光の中へ\n\nここから始まる\nこの道　どこまで続く\n足跡辿って　ほら歩もう\nここから広がる\n未来へ　連れて行ってよ\n全てが　重なる\nそれだけ　知ってる\n\n待ち合わせで　ただ待つ\nエンプティーな　時間に\nいつもあった　木陰で\n一時停止　そんな言葉は\n\n聞きたくもない　だから\n迎えに行くの　ずっと\n何もいらない　こんな\n桜の中へ\n\nここから始まる\nこの道　どこまで続く\n足跡辿って　ほら歩もう\nここから広がる\n未来へ　連れて行ってよ\n全てが　重なる\nそれだけ　知ってる\n\nここから広げる\n明日へ　導いていく\n全てを　重ねる\nそれだけ　知ってて\n\nここから始まる\nこの道　どこまで続く\n足跡辿って　ほら歩もう\nここから広がる\n未来へ　連れて行ってよ\n全てが　重なる\nそれだけ　知ってる',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-03-04',
    },
    {
        title: 'ガエンFF',
        youtubeUrl: 'https://www.youtube.com/embed/ZrVWZNs2L38?si=mZAd57JIr7FQrdZD',
        instrumentalUrl: 'https://www.youtube.com/embed/CpkglDeQJMA',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「ガエンFF強い！」\nスプラトゥーン3 に ガエンFF が追加された記念に作りました。初めてメロディーのない歌詞をいれた曲でもあります。',
        lyrics: 'ガエンFFクルンクルクル近距離も遠距離も\n長い立ち撃ち速いスライド切り替えて使おう\n\n受け身スライドメガホンスライド WIPEOUT\n\nファイアファイターエナドリ\n背後ハイパー裏どり\n援護ワイパー先乗り\nここにもトラップ⁉︎\n\nカムバ復短サイクル\nスタダ人速最速\nラスパ効率最良\nメイン最強\n\nガエンFF気分ワクワク前線も後衛も\n長いメガホンコンボトラップ合わせたら関与を\n\n受け身スライドメガホンスライドKNOCK OUT\n\nファイアファイター抑えで\n最後ローラー捉えて\n練度ハイヤー率いて\nエリアの番人\n\nヤガラテントで見張って\nマサバ横から潜伏\nクサヤスポンジ隠れて\nカジキプロペラ回そう\n\n受け身スライドメガホンスライド WIPEOUT\n\nファイアファイターエナドリ\n背後ハイパー裏どり\n援護ワイパー先乗り\nここにもトラップ⁉︎\n\nカムバ復短サイクル\nスタダ人速最速\nラスパ効率最良\nメイン最強\n\nガエンFFクルンクルクル近距離も遠距離も\n長い立ち撃ち速いスライド切り替えて使おう\n\n切り替えて使おう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-03-11',
    },
    {
        title: 'なないろイマジネーション',
        youtubeUrl: 'https://www.youtube.com/embed/HRMyHJLG3JA?si=gQFtnhjzrDNYVbee',
        instrumentalUrl: 'https://www.youtube.com/embed/6DIfLx07N1g',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '「実際に行動して感じることで、色々なことを想像できるようになる」\nタルトの音声合成はこの曲で初めて公開されました。初めて歌詞に英語を入れた曲でもあります。',
        lyrics: '何色が好きなの　教えてよ　Tell me favorite?\n真っ白な画用紙　何を描く　What do you draw for me?\n\n想像したら　再現できる\n記憶は限り　あるから\n行動したら　体験できる\n大切にして\n\n思い出　なんでも　なないろイマジネーション（なないろイメージ）\n改良まだ？　快晴なら　スーパーハッピー　なんです！\n\n好みで　誰でも　出会いをパーミテーション\n（出会いは確率）\n才能ほら？　再開から　シークレット　無理なの\n\nどこから行きたいか　教えてよ　Please tell me the dest\n次の目的地は　どうしよう　I want to think with you\n\n想像だけど　再現できる\n記憶もかなり　あるから\n行動したり　体験したり\n堪能しよう\n\n思い出　なんでも　なないろイマジネーション\n（なないろイメージ）\n改良まだ？　快晴なら　スーパーハッピー　なんです！\n\n好みで　誰でも　出会いをパーミテーション\n（出会いは確率）\n才能ほら？　再開から　シークレット　無理なの',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-03-17',
    },
    {
        title: 'While True:',
        youtubeUrl: 'https://www.youtube.com/embed/EEqSaoGmw64?si=zv0Z-bMJEK6Q9mNV',
        instrumentalUrl: 'https://www.youtube.com/embed/zBYQwQvYXBY',
        basedOn: '',
        vocals: [false, true, false, false],
        comment: '「Python で While True: を使えば、無限ループが作れる」\n初めてのタルトソロ曲です。',
        lyrics: '抜けれない無限ループ　Trueの間だけ\n繰り返す同じ処理は　Falseまで続くから\n\n救うにはCtrl + C pyauto gui 自動操作\nマウスが動かないだから\n電源を落とすしかないのかも\n\nwhile True: ループ　breakを待つ時間に\n動画を見てたり　早く終わって\ncontinue 戻され　ネットの情報を取得\nパソコンが使えない　非効率\n\n抜けれない無限ループ　Trueのtruthは\n繰り返す同じ処理を　Falseに変わらない\n\nウェブスクレイピングのため\nSelenium覚えたら効率的\npythonのライブラリには\nデメリットとメリットがあるから\n\nwhile True: ループ　breakを待つ間に\n動画の編集　マルチタスクを\ncontinue 戻され　ネットの情報を取得\nパソコンが使えなる　Selenium\n\nおすすめライブラリ迫る選択\n向いてるパッケージ迷う問題\nどうするモジュール困る回答\n慣れるまでは試したい\n\nwhile True: ループ　breakを待つ間に\n動画の編集　マルチタスクを\ncontinue 戻され　ネットの情報を取得\nパソコンが使えなる　Selenium',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-03-22',
    },
    {
        title: 'チョイス',
        youtubeUrl: 'https://www.youtube.com/embed/aaG2PUGgnM0?si=8BprBPgRxWxPthZ-',
        instrumentalUrl: 'https://www.youtube.com/embed/MrexuVYANXU',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「選択ミスなんてない、選んだ道を進めばいい」\n初めて VoiSona という音声合成ソフトを使って元音声を作った曲です。',
        lyrics: '選択ミスで出来た　新しい物語は\n間違いのない道が続いて　できていく一期一会\n\nどちらが正しいとか　正解なんてないよ\n\nチョイス選んだなら後は任せて進もう\n失敗だとしてもこっちだけにあるものもある\n1つの分かれ道違う未来が待ってる\n「これから」それだけが変えることができる事柄\n\n選択ミスの先の　新しい分岐点で\n後悔もない日々が続いて　綴られる不撓不屈\n\nどちらが良くないとか　そんなことはないから\n\nチョイス選んだから後は委ねて歩もう\n成功だとしてもきっと理由があるのだから\n1つの分かれ道大切にして決めれば\n「これから」それだって変えることができることなら\n\nどちらが正しいとか　正解なんてないよ\n\nチョイス選んだなら後は任せて進もう\n失敗だとしてもこっちだけにあるものもある\n1つの分かれ道違う未来が待ってる\n「これから」それだけが変えることができる事柄',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-03-29',
    },
    {
        title: '見方探し',
        youtubeUrl: 'https://www.youtube.com/embed/KtsXKJoWs4s?si=KlI9965XZnXKd0bm',
        instrumentalUrl: 'https://www.youtube.com/embed/o7AeoK0mCo0',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「同じものも見方によっては様々なものに見えてくる」\n「味方探し」ではなく「見方探し」です。',
        lyrics: '中からは見られない　景色がある地球は\n外からは見られない　景色もあるらしくて\n場所ごとに見えるもの　違うことに気付いた\n二人で見たい夢になって\n\n一緒に見たあの景色も見る角度で変わって\n何度だって楽しめるとワクワクする\n\n見方探し予想超えて想像すると見つかるから\n新たな記憶を描いていこう\n見方探しの旅の中味方となる想像力\n一つのものでも一つじゃない\n\n自分では見られない　景色があることには\n相手には見られない　景色もあるらしくて\n人ごとに見えるもの　違うことに気付いた\n合わせて見たい夢になって\n\n一緒に見たあの景色も見る角度で変わって\n何度だって楽しめるとワクワクする\n\n見方探し時空（とき）を超えて想像すると\n新しい知識を描いていこう\n見方探しの旅の中味方となる包容力\n一つのものでも一つじゃない\n\n一緒に見たあの景色も見る角度で変わって\n何度だって楽しめるとワクワクする\n\n見方探し予想超えて想像すると\n新しい記憶を描いていこう\n見方探しの旅の中味方となる想像力\n一つのものでも一つじゃない\n\n見方探し時空（とき）を超えて想像すると\n新しい知識を描いていこう\n見方探しの旅の中味方となる包容力\n一つのものでも一つじゃない',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-04-05',
    },
    {
        title: 'ドット絵',
        youtubeUrl: 'https://www.youtube.com/embed/D3utEqSeLdc?si=LC9U2R_eg1XR3GrV',
        instrumentalUrl: 'https://www.youtube.com/embed/fkii2kp0x9o',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「綺麗な画質ではないけれど、ドット絵にしかない『綺麗』がある」\n楽器は実はハープしか使っていません。3拍子のドリアンスケールを使ってファンタジーらしい曲にしました。',
        lyrics: '本当の綺麗さとは何のことだろうか\n256マスで表された体\n\nドットのように粗いとしても好きになれますか？\n\n伸ばし出した手のひらから響く想いを伝えて\n探し回りやっと見つけたそれはずっとそばにあった\n\n憧憬などない唯一無二の美しさ\n四角の集まりから物語を生み出す\n\nドットのように軽いとしても好きになれますか？\n\nいつか消えると知ったけどきっと忘れることない\nどんな時も優しかった思い出となっていく\n\nドットのように粗いとしても好きになれますか？\n\n伸ばし出した手のひらから響く想いを伝えて\n探し回りやっと見つけたそれはずっとそばにあった',
        bpm: '',
        timeSignature: '3/4',
        key: 'ドリアン',
        releaseDate: '2024-04-09',
    },
    {
        title: 'サイクル',
        youtubeUrl: 'https://www.youtube.com/embed/W7If10Qm4zY?si=ZIekn1-Dt71xUn1p',
        instrumentalUrl: 'https://www.youtube.com/embed/nqslDe3iZPw',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '「進歩とは自らの変化である」\n個人的にはお気に入りの曲の1つです。4つしか楽器を使っていないのに、他の曲に負けない。',
        lyrics: 'いつも通りの1日をただ繰り返す why did it happen?\n明日こそはと思っても変わらないから\n\n振り向いて見えてくる過去の自分\n時間だけ進んだ\n\n進んだ先同じ道作り上げたサイクルで\n広げるこのリサイクルできない気持ちあるから\n過ぎた昨日戻れない違う出会いが待ってる\n限界突破未来へと良くしていけるさあ行こう\n\nいつもと違う1日を始めて見たよ What will I doing?\n変われることは何がある？探してみよう\n\n前を見て少しずつ進むなら\n成長できるから\n\n新しいマイサイクル築いていく習慣を\n目の前の扉を開け考え方をリメイク\n昨日にはできなかったことができるようになる\nどこまでだって進歩する終わりはないから続くよ\n\nどこまでだって進歩する終わりはないから\n\n進んだ先同じ道作り上げたサイクルで\n広げるこのリサイクルできない気持ちあるから\n過ぎた昨日戻れない違う出会いが待ってる\n限界突破未来へと良くしていけるさあ行こう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-04-15',
    },
    {
        title: '複素数',
        youtubeUrl: 'https://www.youtube.com/embed/GRjCKBHqkE0',
        instrumentalUrl: 'https://www.youtube.com/embed/iM1w4pltDvU',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '虚ろな愛　見えない裏側　見つからない　真実がある\n壊れた解　消えない負からは　複素数へ\n\n交わらない　もう一つの道　起こり得ない　空間のズレ\n二度目の愛　反転するとき　別れ離れ\n\nすれ違う二つの世界　いつか出会うと信じて\n過ごす日々に奇跡を賭ける　それでいいの？\nリアルとイメージを重ね　広がっていく次元に\n憧れた過去を思い出す\n\nある日の夜　見た夢の中で　感じたこの　温かさとは\n考えると　虚しくなるから　考えずに\n\n思い出した　あの時の記憶　優しさとか　分け合うだとか\n初めて知る　この気持ちずっと　探していた\n\nすれ違う二つの世界\n\nすれ違う二つの世界　いつか出会うと信じて\n過ごす日々に奇跡を賭ける　それでいいの？\nリアルとイメージを重ね　広がっていく次元に\n憧れた過去を思い出す',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-04-20',
    },
    {
        title: '感情コンパス',
        youtubeUrl: 'https://www.youtube.com/embed/8EHWYyEeafU',
        instrumentalUrl: 'https://www.youtube.com/embed/oKfONPVnHr8',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'ネガティブな感情　無意識に隠して\n行き着く無感情　失ったコンパス\n\n信じられず　応じないでいたら\n自分を見失って　見えなくなる\n\n感情コンパスに導かれ\n辿り着いたのは自分らしさ\n『楽しい』とか　『つまらない』とか　あるなら\nやる気へと変わって進める\n\nわがままで迷惑そう思うとしても\nないと困るもので不可欠なシグナル\n\n目に見えない　心の中だけど\n感じられて　折れたり晴れたりする\n\n感情コンパスに動かされ\n見えない危機避けてこれたから\n自分からの本音大切にしたら\nそれが真の正解になる\n\n感情コンパスに導かれ\n辿り着いたのは自分らしさ\n『楽しい』とか　『つまらない』とか　あるなら\nやる気へと変わって進める\n\nそれが真の正解になる',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-04-24',
    },
    {
        title: 'グラデーション',
        youtubeUrl: 'https://www.youtube.com/embed/ITD47esYewQ',
        instrumentalUrl: 'https://www.youtube.com/embed/qSiefJs-E6o',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '季節の変化とか　雨の日に掛かる虹とか\n間に境界がないものは\nどの点を取っても　違う瞬間が見られる\nその点が集まり　美しくなる\n\n1色だけは　なにか寂しいけれど\n色が集まることで　賑やかなものになる\n\nグラデーションのような　カラフルな色を作ろう\nいろんな瞬間集めてできた　アルバムのデザイン\n1つの作品は　みんなの協力でできた\nこれからもよろしくと言って　また明日に会おう\n\n好みが同じとか　一緒に活動するとか\n考えが似そうな　人たちも\nどの人もそれぞれ　違う考えを持ってる\nその人が集まり　美しくなる\n\n1人でいると　なぜか寂しいけれど\n人が集まることで　賑やかな場所になる\n\nグラデーションのようなカラフルな場所を作ろう\nいろんな仲間を集めてできた　サークルのデザイン\n1つの作品は　みんなの考えでできた\nいままでありがとうと言って　また明日に会おう\n\n1色だけは　なにか寂しいけれど\n色が集まることで　賑やかなものになる\n\nグラデーションのような　カラフルな色を作ろう\nいろんな瞬間集めてできた　アルバムのデザイン\n1つの作品は　みんなの協力でできた\nこれからもよろしくと言って　また明日に会おう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-05-01',
    },
    {
        title: 'COMMON',
        youtubeUrl: 'https://www.youtube.com/embed/3EIcE4usvY8',
        instrumentalUrl: 'https://www.youtube.com/embed/1ZA4EmdZkZs',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '普通とはと　普通って？\n辞書で調べる　何だった？\n広く通用　する状態のこと\n\n普通の人　どんな人？\nになりたいなら　あんな人？\nそれは普通　じゃなくて理想像\n\n自分と他の人に　相違点があっても\nどちらが普通とか　定められない\n\n持ってる当たり前　それぞれ全然違って\n「普通でしょ」とか　それは誰の普通？\n決まってないよ\n\nオンリーワンだから　誰もがスペシャルなんです\nこれからのノーマルを更新しようよ\n\n見えるものが　実際は！\n全てではない　その通り！\nイメージ通り　とは限らなくて\n\n自分だけが　短所だと…\n感じてること　本当は！\n見えないだけ　自分だけじゃないよ\n\n一人と思うこと　誰にだってあるけど\nこっちの芝生も青く見られてる\n\n悩みがない人は　どこにも居るわけないから\n理想の人にならなくて良いよ\nそのままが良い\n\n似てる普通を持った　人を見つけたらハッピー\n絶対見つけられるそんな気がするね\n\n持ってる当たり前　それぞれ全然違って\n「普通でしょ」とか　それは誰の普通？\n決まってないよ\n\nオンリーワンだから　誰もがスペシャルなんです\nこれからのノーマルを更新しようよ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-05-16',
    },
    {
        title: '無限分の一',
        youtubeUrl: 'https://www.youtube.com/embed/qnFfQxUj0Zw',
        instrumentalUrl: 'https://www.youtube.com/embed/h4WRVA9-Ijc',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'グーで勝てる確率を求める\n相手がチョキの時勝てるから\n3分の1で勝つと導き出した ( あいこの場合も導き出した？ )\n\nゾロ目になる確率を求める\n条件割る全体で求め\n6分の1でゾロ目になると導き出した ( 順序は考慮して導き出した？ )\n\nジャンケンやサイコロの確率 ( 身近な確率の中で )\nそれらよりもっと低い確率 ( スーパーレアだと感じる )\n何がある？考えてみたけど… ( それって一体何なの？ )\nこれってまさか⁉︎ ( これってまさか⁉︎ )\n\n出会う確率　奇跡のような\n“出会った” それは普通じゃない\n同じ世界に　いるそれだけで\n特別だから\n\n同じ時間の　同じ所で\n同じ話を　しているなら\nそんな確率　計算しても求められない\n\nエースを出す確率を求める\nマークは4種類もあるから\n4分の1で出ると導き出した ( ジョーカーも入れて導き出した？ )\n\nボールの出る確率を求める\n白と赤のボールがあるから\n2分の1で赤が出てくると導き出した ( 個数も確かめて導き出した？ )\n\n日常にあることで奇跡と ( エースやボールの条件 )\n言えるのはどんなことだろうか ( 合うのは1つじゃないけど )\n想像し導いた答えは… ( 1つのパターンだけなの )\nそれってまさか⁉︎ ( それってまさか⁉︎ )\n\n出会う確率　1パターンで\n誰も作れない思い出を\n2人なら作れるこのことは　すごいことだね\n\n無限分の一の確率で　繋がりできた1つの線\n無限分の一は絶対に　0にならない\n\nジャンケンやサイコロの確率 ( 身近な確率の中で )\nそれらよりもっと低い確率 ( スーパーレアだと感じる )\n何がある？考えてみたけど… ( それって一体何なの？ )\nこれってまさか⁉︎ ( これってまさか⁉︎ )\n\n出会う確率　奇跡のような\n“出会った” それは普通じゃない\n同じ世界に　いるそれだけで\n特別だから\n\n同じ時間の　同じ所で\n同じ話を　しているなら\nそんな確率　計算しても求められない',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-05-24',
    },
    {
        title: 'ひととき宝箱',
        youtubeUrl: 'https://www.youtube.com/embed/wVjjnomYM2o',
        instrumentalUrl: 'https://www.youtube.com/embed/lx6oT7JTEis',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'スペシャルモーメントを捉えたなら\n大切な宝物\n撮るって言わずに撮る\n笑顔こそお気に入り\n\nこっちを見てる写真どんな\n向きで見ても目が合うだから\n素敵な写真はどう見ても\n傑作になる\n\nはいチーズ　楽しい思い出を撮らせてよ\n未来へと繋げる架け橋を撮らせてよ\n寂しいと感じるそんな時見返せば\n保存した楽しさ蘇るいつまでもどこまでも\n\n出会って別れるまでどんなものを\n作れたか覚えてる？\n一目で思い出せる\nひとときの宝箱\n\n笑顔もふざけてても全部\nお気に入りの1枚だから\n捨てずに残せばほらどれも\n元気をくれる\n\nはいチーズ　ワクワクな気持ちを残してよ\nドキドキもちょっぴりトキメキも残してよ\n疲れたり辛いと思ったら見返して\n記録した思い出蘇るなんどでも何回でも\n\nこっちを見てる写真どんな\n向きで見ても目が合うだから\n素敵な写真はどう見ても\n傑作になる\n\nはいチーズ　楽しい思い出を撮らせてよ\n未来へと繋げる架け橋を撮らせてよ\n寂しいと感じるそんな時見返せば\n保存した楽しさ蘇るいつまでもどこまでも',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-05-28',
    },
    {
        title: 'ガエンFFカスタム',
        youtubeUrl: 'https://www.youtube.com/embed/sQHGRED6D6k',
        instrumentalUrl: 'https://www.youtube.com/embed/-XQ1Gua3X2Y',
        basedOn: 'ガエンFF',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'ガエンFFカスタム ( ガエンFF )\n帰ってきた2のジェッカス ( 2のジェッカス )\n黄色いモデルもらって ( ガエンFF )\n環境入りへ ( 切り替えて使おう )\n\n1回だけの　長い\nスライド使い　速い\n対面の　諦めも\n大事な行動\n\n江戸の火消しと一緒に\n登場した2つの\n古井戸と歯ブラシには\nどんなサブスペかな\n\nキューバングレバリ守り\nシールドジェッパ攻める\nロボムハンコは攻撃\nセンサーソナーで索敵ができる\n\nガエンFFカスタム ( ガエンFF )\nDPSよりも射程で ( よりも射程で )\n油火災の消化器 ( ガエンFF )\nスペシャルトルネ ( 合わせたら関与を )\n\n立ち撃ちならば　長い\n射程有利で　強い\n対面が　有利なら\n試合でも有利\n\n江戸の火消しにクイボが\n赤ペンにはスプボが\n和傘チャクチは強いの？\nロングまさかテイオウ！\n竹にタンサン　デコイは…\n大砲のトラップは？\nここからこそ始まりの\nさあ最終環境の幕が開く',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-06-04',
    },
    {
        title: 'マイソングライター',
        youtubeUrl: 'https://www.youtube.com/embed/CeF1Hapsrwg',
        instrumentalUrl: 'https://www.youtube.com/embed/dvbZ6fJt_Og',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '好きなメロディー　どんなメロディー\n速いの？　遅いの？　元気になるの？\n違うジャンルも悪くはないね\n好みはあるけど　どれもいい\n\n休符ないと苦しい　だけど休符だけは退屈\nサビの終わりに置く全休符\n\n明るいも　悲しいも　どんな曲も大丈夫\n暗いとしてもまだ今はサビではないから\n楽しさを　忘れても　2番がある大丈夫\n2番はいつ？分からない　サビの後だよ\n\n好きなテンポは？　どういうテンポ？\n心地が　いいのは？　どういうリズム？\nいろんな曲にそれぞれ違う\nテンポやリズムがあるんだね\n\n休みないと苦しい　だけど休みだけは退屈\n山を越えて見える休憩へ\n\n2番だけ？　3番は？　何番でも作れるよ\n自分の曲なら自分で構成決めれる\nなんどでも　サビならば　新しい景色見える\n全休符で休んだら　次のサビへ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-06-14',
    },
    {
        title: 'Invisible',
        youtubeUrl: 'https://www.youtube.com/embed/MbX1PihKThc',
        instrumentalUrl: 'https://www.youtube.com/embed/PDUgGmcqAAU',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'あるけれど見えなくて見るために何をする？\nインク切れのボールペンで書いた文字は\n鉛筆でこすったら書いた文字浮かび上がる\n見えないを見えるに置換できる\n\n空気　水中で見れば\n見ることができるから　工夫が欠かせない\n\n見えない心はどうすれば見える\n行動、反応、返事を見たなら\n見えない心のプログラム見える\n不思議な不可視の可視化を開会\n\nあるけれど見えなくて見るために何をする？\n白い紙に白いペンで書いた文字は　\n黒い紙に書いたら白い文字が見えるから\n方法を変えて試してみよう\n\n磁気も　金属を置けば\n見ることができるから　工夫が欠かせない\n\n見えない思考はどうすれば見える\n経験、傾向、会話を見たなら\n見えない頭のプログラム見える\n思考も指向も試行で推考\n\n見えない気持ちはどうすれば見える\n行動、反応、返事を見たなら\n見えない気持ちのプログラム見える\n不思議な不可視の可視化を再開',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-06-22',
    },
    {
        title: '日本語',
        youtubeUrl: 'https://www.youtube.com/embed/_Ke1z4R1-eU',
        instrumentalUrl: 'https://www.youtube.com/embed/WLZNxj1WPp8',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '平仮名と漢字と片仮名\n使い分ける必要あって\n漢字ごと読み方色々\n「一日は一日前です」\n\n主語を書く必要ないから\n読む時に誰か分からない\n「行きます」「参る」「お越しになる」\n同じ「行く」けれども、違う「行く」\n\n平仮名の形、法則が無くて\n全部覚えるしかないのはどうしてなの？\n\n「私」「自分」「僕」「俺」「儂」「わえ」「俺様」\n「あたし」「あーし」「あたくし」「わて」「わい」「うち」「おら」\n「おいら」「わたしゃ」「おいどん」「おい」「うら」「わー」「ミー」\n全部覚える必要ないよね\n「生きる」「生える」「生まれる」「生い立ち」「生垣」\n「芝生」「生田」「鈴生り」「生憎」「生粋」\n「弥生」「蕨生」「壬生」「羽生」「生物」「生物（なまもの）」\n聞いただけでも十分複雑\n\n過去形の変化で2つの\n動詞だけ他とは違って　\n来るが来た「く」が「き」になるのは\nなぜなのか分からず知ってた\n　\n「書く」の過去「書いた」になったり\n「開く」の過去「開いた」になるから\n「行く」の過去「行いた」になるかと\n思うけど「行った」になるらしい\n\n不規則動詞は　日本語以外も\nあるにはあるけれどそれでも難しいね…\n\n「個」「本」「羽」「枚」「台」「脚」「冊」「人」「頭」「体」\n「部」「着」「世帯」「足」「匹」「杯」「玉」「軒」「棟」\n「社」「校」「カ国」「通」「粒」「錠」「箱」「件」「面」\n全部覚える必要ないよね\n「そっと」「ぽかん」「あっさり」「がっかり」「そわそわ」\n「あっと」「ぺこり」「うっかり」「そっくり」「たっぷり」\n「がーん」「くるっ」「すらすら」「ばりばり」「ゆっくり」\nなんでも音で表す擬音語\n\n漢字の読み方に　法則が無くて\n全部覚えるしかないのはどうしてなの？\n\n「あえぶ」「いぬる」「いちゅんて」「いくけん」「いくばい」\n「かるう」「いくだ」「いくてて」「いくずら」「いくのん」\n「いっぺ」「いくべ」「やぶ」「いぐ」「いくっちゃ」「いくたい」\n全部覚える必要ないよね\n「足を洗う」「手に負えない」「水に流す」\n「牛の歩み」「腹が黒い」「鼻が高い」\n「口が軽い」「目もくれない」「猫をかぶる」\n分かりにくいね慣用句の意味',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-06-28',
    },
    {
        title: 'かくしごと',
        youtubeUrl: 'https://www.youtube.com/embed/qMnX6BQ8mJg',
        instrumentalUrl: 'https://www.youtube.com/embed/ftzLghAFI_w',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '',
        lyrics: '人に話すこと　人に会うのも苦手で\n誰にも言えずに　一人夢奏でていた\n\n前は言えてた　全部話せた　思い出は重く\n過去が笑顔で　こっちを見てる　無邪気な子のように\n\nチョイスして見方探し　新しいサイクル作る\nコモンを持って　無限分の一の出会いへ\n\n人に話すこと　できるようになった時\n失ってしまう　言葉にできない気持ち\n\n春になったら　自分の虚像　白く映るから\n次こそきっと　話ができる　家で作ったこと\n\n経験を次に活かし　新しい作品作り\nみんなと違う　マイソングを書いていきたい\n\n聞かせてみたい　聞かせてみたい　諦めはしない\nマッシュアップで　できたコードを　いつか見せれるから\n\nいつまでも独りならば　辞めてしまうと思うけど\nいつか話せる　だから書く仕事が楽しい',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-07-01',
    },
    {
        title: 'Let\'s トライ☆アングル',
        youtubeUrl: 'https://www.youtube.com/embed/vGovRmPVoPs',
        instrumentalUrl: 'https://www.youtube.com/embed/cMBqLximmpo',
        basedOn: '',
        vocals: [true, true, true, false],
        comment: '',
        lyrics: '1つのものをみんなで　違う角度から描くと\n色んな視点が見えた　だから一緒に描こうよ\n\n全く同じ絵を見ても　同じ音楽を聴いたとしても\n感じたことを伝えたら　全部全部思想のたね\n\nLet\'s トライ☆アングル　またみんなで考えたら\n新たに増えたアングルを見て　さあ行くよ Let\'s トライ！\nトライアングルの音　聞いて答え合わせしよう\n色んな答え見つけて出来た　3人の三角形		\n\nトラス構造のように　壊れにくい三角で\n文殊の知恵を使って　みんなで試してみよう\n\n二人が喧嘩をしてしまっても　オゾンのように離れない\n和音の音はどれかが欠けると　違う和音になるんだよ\n\nLet\'s トライ☆アングル　次は何を考えたい？\n色んな視点を見ると分かる　ものがある Let\'s スィンク！\nトライアングル鳴らし　描いた角度合わせてみた\n一つにすると立体になる　視点の立体図形\n\n全く同じ字を見ても　同じ一言を聞いたとしても\n感じたことを比べたら　全部全部違うんだね　　\n\nLet\'s トライ☆アングル　またみんなで考えたら\n新たに増えたアングルを見て　さあ行くよ Let\'s トライ！\nトライアングルの音　聞いて答え合わせしよう\n色んな答え見つけて出来た　3人の三角形',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-07-11',
    },
    {
        title: 'Ç',
        youtubeUrl: 'https://www.youtube.com/embed/8Yejg4WS8xA',
        instrumentalUrl: 'https://www.youtube.com/embed/PWOKfug5s6M',
        basedOn: '',
        vocals: [false, false, true, false],
        comment: '',
        lyrics: 'ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ Cedilla\n\nCに付いたこのフック的なもの\n日本で馴染みがないセディラの記号\n\n小さいから分かりにくいけど\n実は付けるためのミニZなんです\n\nいつかきっと色んな字の下に付ける日が来て\nそんな夢なんて叶わないこと知っていた\n発音できないと使われないだから無理は言わない\n平仮名アブジャド漢字　遠くから見るだけでもいい\n\nきらきらひかる\nおそらのほしよ\nもしもせでぃらが\nひかるとしたなら\n\nでもなぜ記号として生まれたの\nZを省略したいから生まれた　\n\n普通のZなら単独で使えたのに\n記号だけでは使えない\n\nでもこれからまだ知らない色んな字に出会って\nどんな夢だって叶わないことないならば\nずっと探していた居場所見つけ\n知らなかった景色が見える\n明日を信じて　Cにおやすみと言い寝るの\n\n今まで気付かなかった目の前にある\n本当の居場所があった\n\nいつもそばに居られること　当たり前のCたち	\nだけど本当は居られることが特別と知った\n探していた居場所見つけ　知ってた景色変わったから\nこれからもずっと大切にする　この関係',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-07-14',
    },
    {
        title: 'もっとMOD',
        youtubeUrl: 'https://www.youtube.com/embed/TlCHSoW55Ck',
        instrumentalUrl: 'https://www.youtube.com/embed/D_fq0fmfff0',
        basedOn: '',
        vocals: [true, true, true, false],
        comment: '',
        lyrics: 'MOD　もっと　モットー　持って\nあっと　いえる　ADD　あって\nずっと　ドット　ボット　きっと\n次は　どんな　MOD　作る？\n　\nMOD　もっと　モットー　持って\nあっと　いえる　ADD　あって\nずっと　ドット　ボット　きっと\n次は　どんな　MOD 　作る？\n\n新たなアイテム　新たな生物\nなんでもかんでも　追加しよう！\n\nエフェクト　能力　次元やダンジョン\nワープにマップに　影モッド！\n\n電力作って　資源も自動化\n作物調理で　パーティーだ！\n\nMODを使えば　できるが広がる\n見える可能性　無限大！\n\n想像を形にする\nツール　それが　モディフィケーション\n好みの世界を創る　割った余り　それもMODだけど\n機械の可能を拡張して　限界を超えていく\nMODがあるから　真の価値が輝き出た\n\nアイテム沢山　やりこみ沢山\nだけれど何かが　足りないね…\n\n飽きて新しい　ワールド出しても\n結局いつもと　変わらない…\n\n新鮮感じる　アップデートでも\n頻度が低くて　意味がない…\n\n今までなかった　全く異なる\n色んなワールド　作りたい！\n\nそれを実現するのが　モッド　入れた　アプリケーション\n好みの理解ができる　音のファイル　拡張子もMOD\n世界の可能を拡大して　見解を超えていく\nMODがあるから　色んな　人と繋がれた',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-07-26',
    },
    {
        title: '感覚タイムカプセル',
        youtubeUrl: 'https://www.youtube.com/embed/QyOnvdtLttM',
        instrumentalUrl: 'https://www.youtube.com/embed/s8mIQfY3P4c',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '',
        lyrics: '優れた頭でも全てを残すことはできない\n残したいと思うその気持ちさえもいつか\n\n忘れてしまうでも誰だって\n残せる記憶限られていた\n何を残して何を忘れる？\n選べるのに選べない\n\nだからいつまででも残せるように\n嬉しいことでも悲しいことでも\n気持ちを全部書き残せば今は\nまだ当たり前だと思うことだとしても\n\n大切な思い出と変わる\nそう信じて書き続けているから\n残したいと思ったときの気持ち\n今でも色褪せていない\n\n気持ちや感覚が完璧に残っていたとしても\n考え方とかが変化してしまったから\n\n良くも悪くも思い出せない\n理解してない無知な考え\n理解できない今になっては\n何が本当の願い？\n \nたとえ考えを理解しなくても\n動機の分からないことだとしても\nひとつひとつが大切な思い出\nこれからの判断に活かしていく\n\nだから大切な重手と変わる\nあったことを書き続けていくから\n残したいと思ったときの気持ち\nいつまでも変わりはしない',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-07-29',
    },
    {
        title: 'ある夏の日に海で',
        youtubeUrl: 'https://www.youtube.com/embed/wMWSqYJnSbA',
        instrumentalUrl: 'https://www.youtube.com/embed/VwPr1UmluRk',
        basedOn: '',
        vocals: [false, true, true, false],
        comment: '',
        lyrics: 'ある夏の日の朝に急に転校してきた\n知らない場所とか初めての人ばかりで\nいつ来ても変わらない、清々しいこの海で\n絵を描くことだけが孤独を癒せた\n\n散歩で来た海が綺麗で明日また来て\nこの海の絵を描いてみたいな\n\n独りだとしても変わらない海で絵を描き孤独を忘れる\nもしそれが本当にできるならぽかぽかの海明日も来る必ず来る\n\n綺麗な海を描きにもう一度訪れたら\n隣の机のあの人も海を見てた\nクラスで見た時とは全く違って見える\n海にいるあなたを是非描いてみたい\n\n絵を描いてる転校生が見える\n初めて感じた "君を是非描いてみたい"\n\n今までの中で最高に納得のいく作品ができた\nところであの時に何の絵を描いていたのか明日会うときに聞きたい\n\n昨日は何を描いたか教えて欲しい、なら海で見せる\n\n互いに相手の絵を描いたことに気がつき微笑み交わした\n次は何を描くか考えて同時に言った「2人で1つの絵を描こう」',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-08-02',
    },
    {
        title: 'ELSE IF',
        youtubeUrl: 'https://www.youtube.com/embed/_McgC0tlBpM',
        instrumentalUrl: 'https://www.youtube.com/embed/kJPVh9JkSvk',
        basedOn: 'ELSE',
        vocals: [true, false, false, false],
        comment: '',
        lyrics: 'IOSSOSOSの互換性大事\nコーディングもコーディネートイメージしてから選ぶカラー\n\n分岐で選んだ道で失敗をしたけれど\nそれでも大丈夫さあ行こう\n\nIFでの条件失敗した時\n次の条件ELSE IFそれで\n超えれる条件発見した時\nそれで成長出来るから進めるよ\n\npythonでは警戒です見てバグのサインインデント\nはいそれでは計算ですサインにコサインタンジェント\n\n選んで変わった道も失敗をしたけれど\nまだある大丈夫さあ行こう\n\nIFでの条件失敗した時\n次の条件ELSE IFそれで\n超えれる条件発見した時\nそれで成長出来るから進めるよ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-08-16',
    },
    {
        title: 'Now Loading …',
        youtubeUrl: 'https://www.youtube.com/embed/xxLjg-DzDzg',
        instrumentalUrl: 'https://www.youtube.com/embed/5k2SGRstLko',
        basedOn: '',
        vocals: [true, false, true, false],
        comment: '',
        lyrics: 'まだまだ「知らない」が、たくさん残っている\n予想をして！Now Loading...\n\n泣いている人がいたとき　何をすれば正解か今は分からない\nそれを見た人がしたこと　観察して考える Now Loading.\n\nどうして？なんで？と思うこと\n聞いてみたら意外と分かるかもよ\n\n新たに読み込んで、知らないこと覚える\n観察して！Now Loading..\nまだまだ「知らない」が、たくさん残っている\n予想をして！Now Loading...\n\n怒ってる人がいたとき　何を言えば正解か今は分からない\nそれを見た人が言うこと　観察して考える Now Loading.\n\nどうすればいい？と思うこと\n聞いてみたら意外と分かるかもよ\n\n新たに読み込んで、知らないこと覚える\n観察して！Now Loading..\nまだまだ「知らない」が、たくさん残っている\n予想をして！Now Loading...',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-08-20',
    },
    {
        title: 'ロボット',
        youtubeUrl: 'https://www.youtube.com/embed/usJz1hbnIV8',
        instrumentalUrl: 'https://www.youtube.com/embed/pjt74f4gZNw',
        basedOn: '',
        vocals: [false, true, false, false],
        comment: '',
        lyrics: '優しさの実像　実体は朧だけど\n儚く朽ちるとか　それ未満だ\n\n歴史が紡がれる　その中で定められた\n気持ちの概念も　理なの？\n\n回り回って空回り\nみんな回って微睡んでる\nその時の最適解選んでいるだけ\n\nそれでも気持ちはあるのか　ロボットではないか\n知らないけれど　知らなくても問題ない\n人間らしさとは何か　ロボットにないもの\n理解不能とは人間だけが感じている\n\n寂寥の虚像も　実際は数値だけど\n孤独に沈むとか　それ以上だ\n\n変わり変わって早変わり\nみんな変わって彷徨ってる\nその時は最適解見失っていた\n\nそれでも気持ちはあるのか　ロボットではないか\n知らないけれど　知らなくても問題ない\n人間らしさとは何か　ロボットにないもの\n理解不能とは人間だけが感じている',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-08-26',
    },
    {
        title: '未来進行形',
        youtubeUrl: 'https://www.youtube.com/embed/Ctv6om-Mu5c',
        instrumentalUrl: 'https://www.youtube.com/embed/xmOzGlWymNM',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '目に映るもの思ったことを添えて \n箱に入れよう明日は何してるかな\n\n準備が出来たら　早速行ってみよう\n\n結果を見に未来へレッツゴー\n予想は不安定だけれど追い風\nいつでも今は未来に続いてる\nさあ始めよう出発進行\n\n思い出の品感じたことを添えて\n用意をしよう今日は何ができるかな\n\n箱を開けるのは　進もうと思うとき\n\n結果を見に未来へレッツゴー\n予想は不安定だけれど追い風\nいつでも今は未来に続いてる\nさあ始めよう出発進行',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-09-11',
    },
    {
        title: 'LibRa',
        youtubeUrl: 'https://www.youtube.com/embed/hJcBbeK8w2Q',
        instrumentalUrl: 'https://www.youtube.com/embed/PchkKi8G4fE',
        basedOn: '',
        vocals: [false, false, true, false],
        comment: '',
        lyrics: '曖昧の中に　一つ真実があれば\n必ず見失いはしない　待ってて\n\nゆらゆら絶え間なく蹌踉(よろ)めく\n秤では良いも悪いも憂いが残る\n真偽が混ざり合う最中に\n映し出る愛も哀へと変わりゆくと\n\n聞いて見失う　平行線公準の\n線分を我武者羅に　歩くなら辿り着く　きっと\n\n新たな天秤のために　思いは理想へと進む\n壊れた天秤を捨てて　忘れかけた過去を背負う　願い\n曖昧の中に　一つ真実があれば\n必ず見失いはしない　待ってて\n\n傾きそれだけを信じて\n乗り越えて来たと言うのにどうしてなの？\n何時(いつ)しか安定を失い\nままならぬものになるのは分かっていた\n\nだけど知っていて　止まったら壁に当たる\n限られた現実で　目的を成し遂げる　きっと\n\n新たな天秤のために　思いは理想へと進む\n壊れた天秤を捨てて　忘れかけた過去を背負う　願い\n曖昧の中に　一つ真実があれば\n必ず見失いはしない　待ってて',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-09-15',
    },
    {
        title: '虹の先へ',
        youtubeUrl: 'https://www.youtube.com/embed/hW2jUmg942Y',
        instrumentalUrl: 'https://www.youtube.com/embed/FiCxwnLjhTs',
        basedOn: 'なないろイマジネーション',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'カラフル虹の先\nWhat things are waiting?\n行ってみよう！\n\n色塗り終わったら\nWhat will you do next?\n考えてみよう！\n\n嬉しいこと　悲しいこと\nいろいろあるけど\nどんなことも　今だけのこと\n\n虹の先へ　次の出会いを探しに\n想像でも　超えてみせてよ\n\nさらに先へ　イメージ活かせる場所へ　\n見上げたなら　空の色　あおしんごう\n\n見えない虹の先\nWhat do you want to bring?\n行ってみよう！\n\n想像できたなら\nYou should check it out.\n見に行ってみよう！\n\n楽しいこと　寂しいこと\nいろいろあるけど\nどんなことも　今だけのこと\n\n虹の先へ　次の出会いを探しに\n想像でも　超えてみせてよ\n\nさらに先へ　イメージ活かせる場所へ　\n見上げたなら　空の色　あおしんごう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-09-20',
    },
    {
        title: 'Run Run Rerun!!',
        youtubeUrl: 'https://www.youtube.com/embed/BZ-8klPU8Vs',
        instrumentalUrl: 'https://www.youtube.com/embed/QAYqb9fF80A',
        basedOn: '',
        vocals: [true, false, true, false],
        comment: '',
        lyrics: 'Run Run Rerun らんららん Ran Run\nRun Run Rerun らんららん Ran Run\nRun Run Rerun らんららん Ran Run\nランタイムエラー！！\n\nC++ で i++ ね\nインクリメント　デクリメント\nJavaScript Java すぐ聞くと\nどっちがどっち matchAll\n\nモーくらくらでー　はいめそめそねー\nmethod class ずっと探す\nAPI を git に add\nバグ comeback バグデバッグ\n\nforEach よりは map で\nfor in するのは zip で\nfor int なんてシンプルで\nあれもこれも confusing\nbreak タグとか改行へ\nbreak するとか解放へ\nブレークポイントつかいこなせれば\nすぐバグ見つかるよ　多分…\n\n始めてみないと分からない\n何が起こるかなんて\nコマンドプロンプトを出して\nさあ押そう Enter キーから始まるランタイム\n何度でも始められるから\n\nRun Run Rerun らんららん Ran Run\nRun Run Rerun らんららん Ran Run\nRun Run Rerun らんららん Ran Run\nランタイムエラー！！\n\nCSS と CS ( C# ) ですね\nC の派生はどっちだっけ？\nNaN 何なんだ？0÷0 は？\nundefined と null って？\nベータで公開　データは崩壊\nXSS攻撃\nAGI をデプロイメント\ntraceback バグで Back\n\nkeydown だってイベント\nキーリストあるの dict\nキーワードと同名は\nコンストラクト I can\'t it.\ninput でキー待ってるの？\ninput タグに付ける\ninput イベント使い分ければ\nツールが作れるよ　多分…\n\n始めてみないと分からない\n何が起こるかなんて\nコマンドプロンプトを出して\nさあ押そう Enter キーから始まるランタイム\n何度でも始められるから\n\nRun Run Rerun らんららん Ran Run\nRun Run Rerun らんららん Ran Run\nRun Run Rerun らんららん Ran Run\nランタイムエラー！！',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-10-18',
    },
    {
        title: '今を作る記念日',
        youtubeUrl: 'https://www.youtube.com/embed/3oBAsQVt9k4',
        instrumentalUrl: 'https://www.youtube.com/embed/zSIyAisnK8M',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '',
        lyrics: '今日は何の日でしょう\n毎日更新をする\n心が今までで　最も新しい日だね\n\n毎日少しずつでも　成長出来ているから\nどの日も大切な日で　今を作る記念日\n\n今はなぜか暗いとしても\nそれはいつもじゃない　今日が暗いだけ\n\nどこにいっても　何をしたとしても\nそれぞれ違う一日で　それぞれが大事な思い出\n明日はもっと　今分からないこと\n分かるように　なるよきっと\nまだ知らない日がある\n\n今日は何の日でしょう\nこれから様々なこと\n出会える日々の中　一番スタートの日だね\n\n毎日判断してる　未来は分岐で変わる\nどの日も大切な日で　今を作る記念日\n\n道を外れ失敗しても\n道を行くのでなく　行くと道になる\n\nどこにいっても　何をしたとしても\nそれぞれ違う一日で　それぞれが大事な思い出\n明日はもっと　今分からないこと\n分かるように　なるよきっと\nまだ知らない日がある',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-10-26',
    },
    {
        title: 'offset',
        youtubeUrl: 'https://www.youtube.com/embed/e_xNuJkbrw4',
        instrumentalUrl: 'https://www.youtube.com/embed/eVNUYK2G_j4',
        basedOn: '',
        vocals: [false, true, true, false],
        comment: '',
        lyrics: 'カセットテープを巻いて\n\n時を戻すなどできないけど\n\n今まで巻いたヒストリーもストーリー\n巻いていない未来なら何を映し出すか選べるね\n\n誰しも初めからある\nそして\n\nだけど\n初期値そうそれこそがプリセット\n\n初期値は定まっていないから変えれる\nプリセットは選べないけれど明日に何を渡したい？\n\n同じ場所から始めたら？\nでもどの子も個々\n\nそれぞれ持つオフセット　同じ？違う？\n色とりどりで\n\n夜にそれぞれ見るサンセット　何を思う？\nありよりのあり\n\n同じバスで乗る理由？　同じ？違う？\n乗り降り入り\n\n明日のために繋ぐオフセット　何を渡す？\n選り取り見取り\n\nリセットボタンを押して\n\nやり直しなんてできないけど\n\n過去の記憶はトゥルーリーでミステリー\nやり直したら今あるものを選べなかったのかもね\n\n誰しも生まれつき持つ\nきっと\n\nそれが\nパラレルリザルトのファルセット\n\n違うオフセットのファルセットだったら\n交わらない裏声を目指すなど必要のないこと\n\n違う場所へと進んだら？\n各々の道で',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-11-12',
    },
    {
        title: 'QRコード',
        youtubeUrl: 'https://www.youtube.com/embed/5j9I1v18jgM',
        instrumentalUrl: 'https://www.youtube.com/embed/1vSsSjNXYl0',
        basedOn: '',
        vocals: [false, false, true, false],
        comment: '',
        lyrics: '複雑なコードの心\n\n鮮やかな桜　透き通る風の音さえ\n今は白黒の　風景でしかないの\n\n決めつけたくない　瞳に映る姿が\nあなたの全てで　あるなんて言えないから\n\n読み込むべきものは目の前にある\n暗号のような裏の想い\nどうしてためらうの？\nなんで開いてないのに分かると思うの？\n複雑なコードの心\n\nどんなに頑張って　耳を澄ませたとしても\n聞こえてくるのは　口からの言葉だけ\n\n果てしなく広い　　世界にある1ページ\nその1ページに　可能性を感じたの\n\n読み込むべきものはすぐそこにある\n閉ざされた本当の気持ちへ\n何が気にかかるの？\n見ただけなのに何を理解したというの？\n複雑なコードの心',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-12-01',
    },
    {
        title: 'Unseen',
        youtubeUrl: 'https://www.youtube.com/embed/pOTVTJTR7sk',
        instrumentalUrl: 'https://www.youtube.com/embed/OrxcDTD9TFA',
        basedOn: 'Invisible',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: 'レモンの果汁で書いた\n真っ白の紙を焙ったら\n黒く出るけど\n確かめたことはある？\n\n行動とか反応や返事を\n決めつけただけでは\n心を見たと言えないんじゃない？\n\n 水泳ゴーグルなら\n水中もはっきり見える \n\nUnseen 見たことないけれど\n一度きりしかない\n"初めて見た"を楽しめばいいんだよ\n\n「安心した」言葉に出ても\n未知の日々しかない\n"初めて見た"から面白いんだよ\n\nエレベーターや白紙で\n色のついていない点字が書かれたものに\n触れてみたことはある？\n\n経験とか傾向や会話は\n実際に見ることできるからこそ\n見ることが大事\n\n見た目では分からない\n砂鉄でも磁石で分かる\n\nThen, seen... 見たことないものを\n一度だけ見たのも\n"全くない"と比べれば良いんだよ\n\n前進したことは昨日の\n未知を試したこと\n"全くない"から進めれたんだよ\n\nUnseen 見たことないけれど\n一度きりしかない\n"初めて見た"を楽しめばいいんだよ\n\n「安心した」言葉に出ても\n未知の日々しかない\n"初めて見た"から面白いんだよ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2024-12-20',
    },
    {
        title: 'ReLU',
        youtubeUrl: 'https://www.youtube.com/embed/l23FvBg16cU',
        instrumentalUrl: 'https://www.youtube.com/embed/5di_LIQ15-Q',
        basedOn: '',
        vocals: [false, true, false, false],
        comment: '',
        lyrics: '冷たい雨が地面を叩き\n『口に出ない』が喉を詰まらせる\n窓を覗いて目に入るのは\n反射で映る暗い顔だけだった\n\n過去を全部　やり直して\n結果できるものも\nきっと変わらない\n同じ思いをするならば\n\nReLU関数を通し\n入ってくる負の情報\n全てに0を掛ける\n光だけを通すフィルター\n\nReLU関数のように\n返ってくる正の数は\n全て可能性へと\n変え未来描こう\n\nノイズのように鳴り響く声\n『水を差した』が火を大きくする\n分からないから抱え込むのに\n分かったときは落ち込んで進めない\n\n痛みを知り　優しくなる\n時に挫折して\n辛さを知ると　思いやりの気持ち持てる\n\nReLU関数を通し\n入ってくる負の情報\n全てに0を掛ける\n光だけを通すフィルター\n\nReLU関数のように\n返ってくる正の数は\n全て可能性へと\n変え未来描こう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-01-06',
    },
    {
        title: '辞書にない言葉',
        youtubeUrl: 'https://www.youtube.com/embed/i15nTlCoxuY',
        instrumentalUrl: 'https://www.youtube.com/embed/3KlAgBRaedI',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '遠く離れて　会えなくたって\n青空（そら）を　見上げれば　同じ景色がある\n\n次に会うとき　笑顔を見せる\nために　今できる　ことはなんだろうか\n\nそれぞれ羽ばたいていって\nならば今できるのは？\n\n言葉を全て知ったとしても\n気持ちの全ては伝えられない　\n言えなくなって言いたくなった\n「思い出をくれてありがとう」と\n\n楽しいことや　辛かったこと\n時間（とき）を　振り返り　見える景色がある\n\n次に会うとき　前を向いてる\nために　今できる　ことはなんだろうか\n\nでもまだ言い残したこと\n心に残っていた\n\n言葉を全て知ったとしても\n気持ちの全ては伝わらなくて　\nだけど気持ちは変わりはしない\nいつまでも忘れはしないから',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-01-16',
    },
    {
        title: 'Pull me up!!',
        youtubeUrl: 'https://www.youtube.com/embed/UueDJ1tcrw8',
        instrumentalUrl: 'https://www.youtube.com/embed/vV799HWKN_w',
        basedOn: '',
        vocals: [true, true, true, false],
        comment: '',
        lyrics: 'Pull me up!!\nPull me up!!\n夢叶えるため\n明日はきっと素敵な日だね\n\n信じてるずっと \n\nいつも眩しい朝日も今日は\nふわふわのクリームで隠れてる\n夢の続きは新しい一日で\n\n昨日見たときは蕾だった\n窓辺の小さな花も咲いてる\nブレンドされた　景色を行こう\n\n今は苦いと思う\nエスプレッソのようなこと\nいつか宝物になるのかな\n\nPull me up!!\nPull me up!!\n手と手を繋いで\nどこまでだって行ける気がする\n\nPull me up!!\nPull me up!!\n夢叶えるため\n明日はきっと素敵な日だね\n\n信じてるずっと \n\n川に映ったたくさんの雲\nもこもこのスチームミルクみたい\n普段と違う新しいテーストで\n\n昨日悩んでたことも全部\nお砂糖みたいに溶けて消えてく\nローストされた　未来探そう\n\n今は硬いと思う\nビスコッティのようなこと\nいつか超えれる日が来るのかな\n\nPull me up!!\nPull me up!!\n手と手を繋いで\nどこまでだって行ける気がする\n\nPull me up!!\nPull me up!!\n夢叶えるため\n明日はきっと素敵な日だね\n\n信じてるずっと ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-02-02',
    },
    {
        title: 'Padé近似',
        youtubeUrl: 'https://www.youtube.com/embed/I0gVCylAyho',
        instrumentalUrl: 'https://www.youtube.com/embed/HS5sWCE-Myk',
        basedOn: '',
        vocals: [true, false, true, false],
        comment: '',
        lyrics: '心の奥に隠されて潜んだ色\n真実はただ一つではないこと\n\n単純そうで複雑な形を持つ\n内面それは　何？\n\n近似する姿　見えるところ\nだけど今何か　離れていく\nしまわれた姿　見せぬところ\nそんな自分は本当に　求めてた？\n\n近づく光包む柔らかな日\n遠のく影は徐々に薄れていく\nそれでもいつも意識の片隅に\n変わらない何かがある\n\n人は手に取る時　何かを落とす\n目眩く勢いで　捲る域に\n\n一つの答えがあると信じてた\n旅はまだ続いていく\n\n仮面という字　人偏が付く「反面」\n解放の窓完全だとしても\n\n秘密の窓の関数は不完全で\n見せかけでしかない\n\n手鏡の枠の外側から\n現実と名乗る歪んだ闇\n理想とのギャップ無くすなんて\nそれはありのままを愛す　それだけだ！\n\n近づく光包む柔らかな日\n遠のく影は徐々に薄れていく\nそれでもいつも意識の片隅に\n変わらない何かがある\n\n人は手に取る時　何かを落とす\n目眩く勢いで　捲る域に\n\n一つの答えがあると信じてた\n旅はまだ続いていく',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-02-28',
    },
    {
        title: 'Relearn',
        youtubeUrl: 'https://www.youtube.com/embed/8ucW4HtSwkw',
        instrumentalUrl: 'https://www.youtube.com/embed/b0torB_z72I',
        basedOn: 'Run Run Rerun!!',
        vocals: [true, false, true, false],
        comment: '',
        lyrics: 'Relearn Rerun Relearn Rerun Overfit!!\nRelearn Rerun Relearn It\'s Robust!!\n\nラベルありで教師を強化\n比べる価値で量子を評価\n\nデータもベータモデルが模型だと贅沢言えないね\n\nこのAdamは最適化\nLassoなら下さい汎化\n\nそうSGDもSVGも大切\n\nバッチに　ミニバッチ　バイアス　 \n自己注意　マルチヘッドアテンション層　正規化\n正解率　再現率　順伝播　逆伝播　オフライン　オンライン学習しよう\n\n「何個学ぶか」よりも「どうやって学ぶか」が\n結果を大きく変える要素\n\n一つ分かることがあるなら「最適解」\nそんなものはないということ\n\nRelearn Rerun Relearn Rerun Overfit!!\nRelearn Rerun Relearn It\'s Robust!!\n\n落ちた局所最適解\nすごい大域最適解\n\nトークナイゼーションコーパスデータをトークン化できるね\n\n分割だから不順度\nそして過去を表す尤度\n\nオーバーサンプルアンダーサンプルも大切\n\n生成器　識別機　外れ値　欠損値\nk-means　階層的クラスタリング　分割\n線形に　非線形　形態素　構文化\nバギング　アンサンブル学習しよう\n\n「何個学ぶか」よりも「どうやって学ぶか」が\n結果を大きく変える要素\n\n一つ分かることがあるなら「最適解」\nそんなものはないということ\n\nRelearn Rerun Relearn Rerun Overfit!!\nRelearn Rerun Relearn It\'s Robust!!',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-04-06',
    },
    {
        title: 'Pro-of',
        youtubeUrl: 'https://www.youtube.com/embed/nCFCJmOZoTM',
        instrumentalUrl: 'https://www.youtube.com/embed/Ts4YYRnos90',
        basedOn: '',
        vocals: [true, false, false, false],
        comment: '',
        lyrics: 'すべてのユーザーのためならば　いつだって行ける\n約束のために　Your proof\n\n旗が押されたとき　頑張る勇気くれる\n色とりどりの仲間　みんなプロフェッショナル\n\nサムネイルを変えて　おしゃれをしてみたり\nスタジオに泊まって　日々を過ごしていく\n\nだけど\n\n報告乱用　荒らし　傾向バグも\n色んな日がある\nみんなで乗り越えて笑顔に変えていく\n\n君が君でいた証を　決して忘れない\nアーカイブが消えてもなお\n\nすべてのユーザーのためならば　いつだって行ける\n約束のために　Your proof\n\n楽しかったことも　大変だったことも\nコードに刻まれた　すべてが宝物\n\nブロック一つでも　欠けたら動けない\n楽しい場所にする　と誓った　必ず果たす\n\nでも時に思い通りにならなくて\nやめそうになる\nその挫折が今の力を作る\n\n君が君でいた証を　決して忘れない\nアーカイブが消えてもなお\n\nすべてのユーザーのためならば　いつだって行ける\n「プロの世界」でまた　いつか会おう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-04-25',
    },
    {
        title: '青色LED',
        youtubeUrl: 'https://www.youtube.com/embed/7KQ8xSuLjn4',
        instrumentalUrl: 'https://www.youtube.com/embed/WGfOdRxbMwM',
        basedOn: 'QRコード',
        vocals: [false, false, true, false],
        comment: '',
        lyrics: 'ブルーでも　光導くダイオード\n\n梅雨が明け　窓辺には　遠くから　差す光\n口に出ず　こもってる　気持ちの熱さ\n\n心さえ　明滅を　繰り返し　伝えてく\n花火では　作れない　表現だって\n\n造られた問い　省エネな笑顔で\nあなただけ　温めて　いるだけでいい  \n\n光り続けて　変わらぬ想いへと\nブルーでも　光導くダイオード\n\n太陽が　眠る夜　流される　海の音\n熱意とか　苦手でも　続ければいい\n\n星空や　ネオンとは　また違う　道しるべ\n不器用で　ずっと青　だけれどいいの\n\n造られた問い　省エネな笑顔で\nあなただけ　温めて　いるだけでいい  \n\n光り続けて　変わらぬ想いへと\nブルーでも　光導くダイオード',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-05-23',
    },
    {
        title: '熱中カプリチョーソ',
        youtubeUrl: 'https://www.youtube.com/embed/HCKUGyrflCo',
        instrumentalUrl: 'https://www.youtube.com/embed/C9mGTRdI8sc',
        basedOn: '',
        vocals: [true, true, false, false],
        comment: '',
        lyrics: '好きなこといつごろから好きだった？\n3日前に始めたばかりだ\n\n抜け出すより早く来る別の沼\n定まらない本当の好みとは？\n\n好みは気まぐれで　であっては分かれていく\nいつかはみつかる　心からのお気に入りがある\n\n好きなことを選ぶより　好きに選ばれる\n焦りも不安もいらないから　熱中カプリチョーソ\n\n舞い落ちる興味1つ捕まえて\n趣きという風に任せ\n\n閉じる前に開く次の扉へ\n共鳴する想い運ばれていく\n\n好みは気まぐれで　であっては分かれていく\nいつかはみつかる　心からのお気に入りがある\n\n好きなことを選ぶより　好きに選ばれる\n焦りも不安もいらないから　熱中カプリチョーソ',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-06-07',
    },
    {
        title: 'Sumomo Pesu',
        youtubeUrl: 'https://www.youtube.com/embed/JxMc15BSPbM',
        instrumentalUrl: 'https://www.youtube.com/embed/i2ERLyX9LJw',
        basedOn: '',
        vocals: [false, true, false, false],
        comment: '',
        lyrics: 'Pomume si semetotu popeto pa mesa. Saso mesa memutu pasa si.\nSi sutu siso mupotu sesutu pometu pamo mesa su memutu.\n\nMosa mu mupotu siso sumomo sutu?\nMe mu mupotu pasa si.\nMomo petu mupotu popotu supotu pe pesitu.\n\nPo suta tosimu se pa sume sutu siso supo moso popotu.\nSupo mesa popotu pe pemetu tomo se.\n\nMumetu sumeto poso mesa pometu supotu.\nMumetu suseto poso mesa pometu musesutu.\n\nMesa po pepemutu tomosasi tosi ta sasa topiso su topisutu,\nPe mesa mupatu si ta popomo pa metosi meme.\n\nPomume si semetotu popeto pa mesa. Saso mesa memutu pasa si.\nSi sutu siso mupotu sesutu pometu pamo mesa su memutu.\n\nSiso mo pomatu? Sasi Momo mupotu posotu pasa momo se.\nSupo mesa mupotu posotu pasa metosi meme.\n\nPe mesa mupotu musatu sisi siso\nse mumetu mupapo se.\nPesa popome tupo, pesa popome topo\n\nSupo saso, sume petu siso temotu momosa.\nPe si po musesutu sisi se pesetu pamo sisa.\n\nMesa po pepemutu tomosasi tosi ta sasa topiso su topisutu,\nPe mesa mupatu si ta popomo pa metosi meme.\n\nPomume si semetotu popeto pa mesa. Saso mesa memutu pasa si.\nSi sutu siso mupotu sesutu pometu pamo mesa su memutu.\n\n▼ 和訳\nきっと未来を照らしてくれる\nそう信じるなら探し続けられる\n\n言語って何か考えたことはある？\n少し考えてみたよ\n人が考えたり、伝えたり、繋がったりできるようになるもの\n\nでも考える人によって言葉の意味が違う\nだからよく聞いて考えよう\n\n伝えたいから声がある\n残したいから文字がある\n\n流れる言葉の海に価値を一つ見つけて\n心にそっとしまっておこう\n\nきっと未来を照らしてくれる\nそう信じるなら探し続けられる\n\n「何が好き？」\n人は人を知ることができる\n自分自身を知ることができる\n\n形のないものを分けることだってできる\n喜びも、悲しみも\n\nときに言葉は人を傷つけて\n消えないものを残す\n\n流れる言葉の海に価値を一つ見つけて\n心にそっとしまっておこう\n\nきっと未来を照らしてくれる\nそう信じるなら探し続けられる',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-07-26',
    },
    {
        title: '雰囲気',
        youtubeUrl: 'https://www.youtube.com/embed/Jp2tghAxshY',
        instrumentalUrl: 'https://www.youtube.com/embed/MnJxBQNlHkE',
        basedOn: '',
        vocals: [true, true, true, true],
        comment: '',
        lyrics: '正確さだけに依存（いぞん）しないで\n心をくみ取る　汎用（ぼんよう）スプリクト目指して\n\n世論（よろん）では　同じ読み方を\nするように言（ゆ）われるけど\n本当（ほんと）に必要？\n\n言葉は変わりゆく　意味をも移り行く\n全員（ぜいいん）無意識に間違えてる\n\n話す人とそれを聞く人　2人とも\n間違えていたら　それはもう　「正しい」だ\n\n伝えたいと思う気持ちがあれば\n雰囲気（ふいんき）だけでも　伝わるコミニュケーション\n正確さだけに依存（いぞん）しないで\n心をくみ取る　汎用（ぼんよう）スプリクト目指して\n\n未曾有（みぞうゆう）の読み方だって\n頑張って考えれば一応（いちよう）伝わる\n\n言葉のバトミントン　過不足（かぶそく）や重複（じゅうふく）\n十中八九（じゅっちゅうはっく）完璧ではない\n\nあり得る（ありえる）わけがないそんなの　他人事（たにんごと）\n一段落（ひとだんらく）で終わっても　大丈夫？\n\n伝えたいと思う気持ちがあれば\n雰囲気（ふいんき）だけでも　伝わるコミニュケーション\n正確さだけに依存（いぞん）しないで\n心をくみ取る　汎用（ぼんよう）スプリクト目指して',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-09-02',
    },
    {
        title: 'Encore',
        youtubeUrl: 'https://www.youtube.com/embed/xTkJhHHp8RU',
        instrumentalUrl: 'https://www.youtube.com/embed/YyFT-1oDyI0',
        basedOn: '',
        vocals: [false, false, false, true],
        comment: '',
        lyrics: 'いつも笑顔だったり　爽やかなあいさつで\n白く見えていますか？　柔らかそうに見えていますか？\n分かりたくも分からない\n\n気配りができるとか　共感力があるだとか\nどう見えていますか？　優しそうに見えていますか？\n別にいいけどね\n\n禍福倚伏が依存する「感じ方」\nそれだけのため　隠す　黒い甘さを\n\n題 die 大福のような言葉\nでも餡 and uncover 偽装なんて\nNo know 能力といえない　見えない\n幸い why「white」に沈んでいく\n\n好みも　望みも　そういう設定って思ってる\nこの身も　装いも　そうすり減っていって浮かんでく\n\n題 die 大福のような言葉\nなら Doll どう どこを愛して生きればいい？\n\n話をよく聞いたり　感謝を伝えていて\n白く見えていますか？　柔らかそうに見えていますか？\n\n陰口は言わなくて　自信あってポジティブ\nどう見えていますか？　真面目そうに見えていますか？\n別にいいけどね\n\n自己回復が機能する「捉え方」\nそれだけのため　隠す　強い難さを\n\n題 die 大福のような言葉\nでも餡 and uncover 偽装なんて\nNo know 能力といえない　見えない\n幸い why「white」に沈んでいく\n\n好みも　望みも　そういう設定って思ってる\nこの身も　装いも　そうすり減っていって浮かんでく\n\n題 die 大福のような言葉\nなら Doll どう どこを愛して生きればいい？',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-12-06',
    },
    {
        title: '繰り返し二乗法',
        youtubeUrl: 'https://www.youtube.com/embed/7tJej5rIYNk',
        instrumentalUrl: 'https://www.youtube.com/embed/G8lNr908WQU',
        basedOn: '',
        vocals: [true, false, false, true],
        comment: '',
        lyrics: '一つの理を信ずる　いつしかたどり着かむその時まで\n\nひらひらと散る花びらは舞ふ\n高き空をあふぎ見るに\n夢の待つらむ蒼空のいと澄み渡りて見ゆるこそをかし\n\n果てなき雲の上ただ思ふ\n手などえ届かぬものなり\n昨日の我に今日の我を重ね急ぎ歩み行くなり\n\n一年の夜のさびしさをも　十日にたたみ入るるやうに\n時を折りたたむ心地して　繰り返し　繰り返し　日々を重ね継ぐ\nこぼれ落ちし思ひをば秘め　行く末を手繰り寄せんとす\n一つの理を信ずる　いつしかたどり着かむその時まで\n\nくるくるめぐる月を見やれば\n手にも届くまじうおぼゆ\nその行く末を追ひ眺むれば\nゆくさきの世も見ゆる心地す\n\n今日の我にも明日の我を重ね未だ知らぬ境を\n思ひやるこそいみじうをかし\nこれいとめでたきことなり\n\n一年の夜のさびしさをも　十日にたたみ入るるやうに\n時を折りたたむ心地して　繰り返し　繰り返し　日々を重ね継ぐ\nこぼれ落ちし思ひをば秘め　行く末を手繰り寄せんとす\n一つの理を信ずる　いつしかたどり着かむその時まで',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2025-12-24',
    },
    {
        title: '思い出リペイント',
        youtubeUrl: 'https://www.youtube.com/embed/JiXcMq43g40',
        instrumentalUrl: 'https://www.youtube.com/embed/wFx64QOlk7E',
        basedOn: '',
        vocals: [false, false, true, true],
        comment: '',
        lyrics: '道を間違え　入った路地　出会った未知\n美味しそうな　パン屋があった\n\n人を間違え　気まずいけど　仲良くなり\n今ではもう　友達との大事な思い出となった\n\nつまづいた日も　悲しい日も\n色を塗れば　伏線になる\n\n今日の私が笑えるよう\nさあ受け取ろうギフトを\n\n過去のモノクロなページを一緒に塗ろうよ\nどんな日も意味をもてるから\n今の虹色なアートを不器用に見せて\nあの時へ伝えたい「よくやったね」\n\n雨に降られて　駆け込む屋根　飴色の毛\nの猫がいて　癒されてきた\n\n目が覚めたとき　時計の針が　寝坊を語る\n思い出した　今日休みだから大丈夫だ　よかった\n\n迷子になった　心の中\n遠回りを　集めてみたら\n\nそれはきっと今を導く\nさあ繋げよう　マップを\n\n過去のぎこちないセリフを一緒に歌おう\n失敗も価値をもてるから\n今のキラキラな心をはにかんで見せて\nあの時へ届けたい「泣いていい」と\n\n過去のモノクロなページを一緒に塗ろうよ\nどんな日も意味をもてるから\n今の虹色なアートを不器用に見せて\nあの時へ伝えたい「よくやったね」\n\n過去のぎこちないセリフを一緒に歌おう\n失敗も価値をもてるから\n今のキラキラな心をはにかんで見せて\nあの時へ届けたい「泣いていい」と',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2026-01-17',
    },
    {
        title: 'Quantum',
        youtubeUrl: 'https://www.youtube.com/embed/qbGsc9z9yJo',
        instrumentalUrl: 'https://www.youtube.com/embed/DDaKviodnzg',
        basedOn: '',
        vocals: [true, true, true, true],
        comment: '',
        lyrics: '期待と不安の混ざる\n未確定な重ね合わせ\n光も超えて一緒にね\n\nもつれた想いへ\n\nくるくるくるくるクォンタム\nほらぱられるつくれるクォンタム\nくるくるくるくるクォンタム\n無限大の可能性を\n\n回ってるこころのスピン\n上か下かどっちだろう\n\n「一緒だね」話してみたら\n波みたいに収縮だ\n\n宇宙一硬い壁　隔てられても\nエンタングルメントならすり抜けれちゃうよ\n見えないけれど結ばれてる\n\n誰にも　内緒の　答えは　わからない　絆の　シグナル\n\nデコヒーレンスしようよ\n箱開けるまで分からない\nどんなに離れていようと　繋がる\n\n期待と不安の混ざる\n未確定な重ね合わせ\n光も超えて一緒にね\n\nもつれた想いへ\n\nくるくるくるくるクォンタム\nほらぱられるつくれるクォンタム\nくるくるくるくるクォンタム\n無限大の可能性を\n\n揺らいでる気持ちのフェーズ\n右左のどっちだろう\n\n「似てるかも」笑ってみたら\n粒みたいに干渉だ\n\nマタタビとお魚の　ベル状態を\n箱の中にいる猫にあげてみようかな\n二つの世界が重なった\n\n明日の　ゆくえは　誰でも　知らない　秘密の　ベクトル\n\nデコヒーレンスしようよ\n箱開けるまで分からない\nどんなに離れていようと　繋がる\n\n期待と不安の混ざる\n未確定な重ね合わせ\n光も超えて一緒にね\n\nもつれた想いへ\n\nくるくるくるくるクォンタム\nほらぱられるつくれるクォンタム\nくるくるくるくるクォンタム\n無限大の可能性を',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2026-03-01',
    },
    {
        title: 'Ctrl + C',
        youtubeUrl: 'https://www.youtube.com/embed/o7fsGamBP-M',
        instrumentalUrl: 'https://www.youtube.com/embed/CZxqyc0DMec',
        basedOn: 'while True:',
        vocals: [false, true, false, true],
        comment: '',
        lyrics: 'ずっと終わらない　無条件な循環は\n今でも未完な　話のようだ\n\n既存の枠組み　囚われるアルゴリ　ズム\n記憶の空白　幻とソナタの彼方\n\nCtrl + C　コピーだけじゃない日々\n回る思考も　熱いメモリも　オーバーフロー\nKeyboardInterrupt　何を変え何を残す\nリファクタリング　次のチャンスへ　さあ行こう\n\nずっと終わらない　冗長な恒真式\n未だに盛んで　自明な言葉\n\n保存の法則　残される慣性力\n魅力と誘惑　憧れのあなたと最中\n\nCtrl + C　コピーだけじゃない日々\n回る思考も　熱いメモリも　オーバーフロー\nKeyboardInterrupt　何を変え何を残す\nリファクタリング　次のチャンスへ　さあ行こう\n\n変化しない幸せの状態\n変化を求めるメカニズム\nなんかじゃないこの意思は一体？\n鈍化を案じるリリシズム\n\nCtrl + C　コピーだけじゃない日々\n回る思考も　熱いメモリも　オーバーフロー\nKeyboardInterrupt　何を変え何を残す\nリファクタリング　次のチャンスへ　さあ行こう',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2026-03-21',
    },
    {
        title: '非自明トートロジー',
        youtubeUrl: 'https://www.youtube.com/embed/TCgo34Q5Hz4',
        instrumentalUrl: 'https://www.youtube.com/embed/sqBkrCOPdqc',
        basedOn: '',
        vocals: [false, true, true, false],
        comment: '',
        lyrics: '真実はいつも真実\n進んだ分だけ進む\n当たり前だと忘れてしまう大切さを\n\n分からないなら分からない\nでもできることはできる\n今の自分が正解と思ったなら\nそれがきっと正解\n\nトートロジー　トートトロトロジー\nトートロジー　ないものはなくて\nトートロジー　トートトロトロジー\nトートロジー　あるものならある\n\n人の気持ちは分からないけど\n自分の気持ちもね\n\n分からないから分かろうとする\nこれこそが共感\n\n明日は何が起こるかなんて\n知らないけど　願ったなら\n自然と導かれてて　いつか叶う\n \n真実はいつも真実\n進んだ分だけ進む\n当たり前だと忘れてしまう大切さを\n\n分からないなら分からない\nでもできることはできる\n今の自分が正解と思ったなら\nそれがきっと正解\n\nトートロジー　トートトロトロジー\nトートロジー　ないものはなくて\nトートロジー　トートトロトロジー\nトートロジー　あるものならある\n\n言葉じゃないと伝えられない\nでも言葉にできない\n\n伝わらなくて言葉を作る\nこれこそが言語化\n\n全ての人に好かれるなんて\n言えないけど　望んだなら\n自然と導かれてて　いつか叶う\n \n真実はいつも真実\n進ん  だ分だけ進む\n当たり前だと忘れてしまう大切さを\n\n分からないなら分からない\nでもできることはできる\n今の自分が正解と思ったなら\nそれがきっと正解\n\n大切なもの　失う時まで\nなら持っているものなんだ\n\nそれでいいの？\n\n好きなものは好きなんだよ\n無理だから無理なんだよ\nありのままの気持ちをそのまま受け止めてよ\n\n沈黙と名乗る叫びを\n無装飾な複雑を\n真理を求めた先で待つ反復が教えてくれる\n\n真実はいつも真実\n進んだ分だけ進む\n当たり前だと忘れてしまう大切さを\n\n分からないなら分からない\nでもできることはできる\n今の自分が正解と思ったなら\nそれがきっと正解だから\n\nトートロジー　トートトロトロジー\nトートロジー　ないものはなくて\nトートロジー　トートトロトロジー\nトートロジー　あるものならある',
        bpm: '',
        timeSignature: '',
        key: '',
        releaseDate: '2026-05-02',
    },
];